// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/speaking": {
    params: {};
  };
  "/publications": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/cv": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/speaking" | "/publications" | "/testimonials" | "/cv";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Speaking.tsx": {
    id: "pages/Speaking";
    page: "/speaking";
  };
  "./pages/Publications.tsx": {
    id: "pages/Publications";
    page: "/publications";
  };
  "./pages/Testimonials.tsx": {
    id: "pages/Testimonials";
    page: "/testimonials";
  };
  "./pages/CV.tsx": {
    id: "pages/CV";
    page: "/cv";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Home": typeof import("./app/routes/Home.js");
  "pages/Speaking": typeof import("./app/routes/Speaking.js");
  "pages/Publications": typeof import("./app/routes/Publications.js");
  "pages/Testimonials": typeof import("./app/routes/Testimonials.js");
  "pages/CV": typeof import("./app/routes/CV.js");
};