// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/speaking": {
    params: {};
  };
  "/publications": {
    params: {};
  };
  "/publications/:id": {
    params: {
      "id": string;
    };
  };
  "/testimonials": {
    params: {};
  };
  "/cv": {
    params: {};
  };
  "/prototype": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/speaking" | "/publications" | "/publications/:id" | "/testimonials" | "/cv" | "/prototype";
  };
  "routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Speaking.tsx": {
    id: "routes/Speaking";
    page: "/speaking";
  };
  "routes/Publications.tsx": {
    id: "routes/Publications";
    page: "/publications";
  };
  "routes/PublicationArticle.tsx": {
    id: "routes/PublicationArticle";
    page: "/publications/:id";
  };
  "routes/Testimonials.tsx": {
    id: "routes/Testimonials";
    page: "/testimonials";
  };
  "routes/CV.tsx": {
    id: "routes/CV";
    page: "/cv";
  };
  "routes/Prototype.tsx": {
    id: "routes/Prototype";
    page: "/prototype";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/Home": typeof import("./app/routes/Home.tsx");
  "routes/Speaking": typeof import("./app/routes/Speaking.tsx");
  "routes/Publications": typeof import("./app/routes/Publications.tsx");
  "routes/PublicationArticle": typeof import("./app/routes/PublicationArticle.tsx");
  "routes/Testimonials": typeof import("./app/routes/Testimonials.tsx");
  "routes/CV": typeof import("./app/routes/CV.tsx");
  "routes/Prototype": typeof import("./app/routes/Prototype.tsx");
};